<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cuemon.Extensions.AspNetCore.Mvc.Formatters.Newtonsoft.Json" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRT_Data\CRT_Data.csproj" />
    <ProjectReference Include="..\CRT_Entity\CRT_Entity.csproj" />
  </ItemGroup>

</Project>
